### ISSUE TITLE
Grammar railroad diagram

### ISSUE THREAD

**Issue by mingodad** [WardBrian/tree-sitter-stan#1]
Using this page https://meimporta.eu/tree-sitter/json2ebnf.html we can get a navigable railroad diagram for tree-sitter grammars like this project.

See also https://github.com/tree-sitter/tree-sitter/issues/2268 .

Cheers !

**Comment by WardBrian** [comment]
Cool, thanks for the links. I'm not sure there's anything to immediately do with these diagrams, but they're certainly interesting
