### ISSUE TITLE
Add tree-sitter-stan to Zed

### ISSUE THREAD

**Issue by spinkney** [WardBrian/tree-sitter-stan#2]
Would you be willing to add this to the Zed editor? I believe it's fairly easy https://github.com/zed-industries/extensions/blob/main/AUTHORING_EXTENSIONS.md.

**Comment by WardBrian** [comment]
It seems like there doesn't need to be any changes here, someone would just need to make a repo which mentions this one in its `[grammars.stan]` section. Am I missing something?

**Comment by spinkney** [comment]
Zed puts a link to the maintainer and I wasn't comfortable forking and having my name there. If you're ok with that then I can do it.

**Comment by WardBrian** [comment]
Is it not ok to have you be the extension maintainer but have it reference this repo?

**Comment by WardBrian** [comment]
See https://github.com/WardBrian/zed-stan-extension
